spring:
  datasource:
    url: jdbc:mysql://mysql:3306/jjlcDB
    username: admin
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080